### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by allench119** [subdavis/subdavis.github.io#1]
so today one of my friends searched my github username then found it appears in this repo. It turns out to be the info we submitted when applying to hackNC. Everything is stored in plaintext in responses.csv and seems everyone can just come and look at it as well. I'm okay with my stuff being exposed out but I'm pretty sure there's people out there who definitely dont want this to be placed in public. Guess privatizing this repo could be a easy and nice solution. I would appreciated it so much if you can move our informations to a safer place :) thanks in advance

**Comment by subdavis** [comment]
Oh my god.  I am _so_ sorry.  This somehow got dragged into the wrong repo and I missed it as part of a whole directory commit.  I will be moving this repo to private until I can be sure the info is gone.  Thank you for messaging me.  This was my fault personally and has nothing to do with the rest of the HackNC planning team.
